# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cb1f5f8b5fffffe441893c88c882e999e8790a4b5b823e6d972514e49f943e77efc29df439515c2fa9b97ccd5d39850c8a60af0fca7be00ea49463d44fca8dd

test:
  secret_key_base: 6c94db392c2ad34f7444fedb352286a9d557a0ed0d6d869f4c7a23b2b79939b26411056abb146a12dd268dc3d7af0d568cede224d40919a49a26a18f9dfa6d4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
